### ISSUE TITLE
Error when fetching SI_EF_OPTIMAL and some other parameters

### ISSUE THREAD

**Issue by olugovoy** [ropensci/nasapower#34]
Hello,
I cannot make 'get_power' working for some parameters like "SI_EF_OPTIMAL". They can be accessed using NASA's web interface:
<https://power.larc.nasa.gov/downloads/POWER_SinglePoint_Climatology_033d04N_093d00E_8ddb2015.txt>
which creates this order:
<https://power.larc.nasa.gov/cgi-bin/v1/DataAccess.py?&request=execute&identifier=SinglePoint&parameters=SI_EF_TILTED_SURFACE&userCommunity=SSE&tempAverage=CLIMATOLOGY&outputList=ASCII&lat=33.4000&lon=93.0000>
Here is the code I use: 
```r
sol_daily_BJ <- get_power(community = "SSE",
                          lonlat = c(93, 33.4),
                          pars = c("SI_EF_OPTIMAL"),
                          temporal_average = "CLIMATOLOGY"
)
```
Which returns:
"Error: 
Something went wrong with the query, no data were returned.
 Please see <https://power.larc.nasa.gov> for potential server issues."
I'm not sure if this is the package or the POWER issue, or I'm just writing it wrong way.
Here is my system info:
> devtools::session_info()
- Session info --------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2019-04-05

**Comment by adamhsparks** [comment]
Thanks for reporting this. I'll have a look and see what I can do to fix it.

**Comment by adamhsparks** [comment]
Ok, I'm trying to understand what's going on here. This query using the parameter, `SI_EF_TILTED_SUFACE`, returns the `SI_EF_OPTIMAL` that you're asking after. However, if I just query `SI_EF_OPTIMAL`, I get the same response that you do. Oddly it is listed as a valid parameter as are the other values in the returned values. 

These aren't values that I typically work with, so I'm not familiar with them, but I've not seen the API return a `data.frame` with multiple parameters like this when querying just one `pars` value.

```r
> sol_daily_BJ <- get_power(community = "SSE",
                             lonlat = c(93, 33.4),
                             pars = "SI_EF_TILTED_SURFACE",
                             temporal_average = "CLIMATOLOGY"
)
> sol_daily_BJ
NASA/POWER SRB/FLASHFlux/MERRA2/ 0.5 x 0.5 Degree Climatologies  
 22-year Additional Solar Parameter Monthly & Annual Climatologies (July 1983 - June 2005), 30-year Meteorological and Solar Monthly & Annual Climatologies (January 1984 - December 2013)  
 Location: Latitude  33.4   Longitude 93.0  
 Elevation from MERRA-2: Average for 1/2x1/2 degree lat/lon region = 4808.03 meters   Site = na  
 Climate zone: na (reference Briggs et al: http://www.energycodes.gov)  
 Value for missing model data cannot be computed or out of model availability range: NA  
 
 Parameters: 
 SI_EF_TILTED_SURFACE SRB/FLASHFlux 1/2x1/2 Solar Irradiance for Equator Facing Tilted Surfaces (Set of Surfaces) (kW-hr/m^2/day) ;
 SI_EF_OPTIMAL SRB/FLASHFlux 1/2x1/2 Solar Irradiance Optimal (kW-hr/m^2/day) ;
 SI_EF_OPTIMAL_ANG SRB/FLASHFlux 1/2x1/2 Solar Irradiance Optimal Angle (Degrees) ;
 SI_EF_TILTED_ANG_ORT SRB/FLASHFlux 1/2x1/2 Solar Irradiance Tilted Surface Orientation (N/S Orientation) ;
 Note(s): ;
 Northward facing tilted surfaces are designated negative (-)  
 
# A tibble: 8 x 16
    LON   LAT PARAMETER JAN   FEB   MAR   APR   MAY   JUN   JUL   AUG  
  <dbl> <dbl> <chr>     <chr> <chr> <chr> <chr> <chr> <chr> <chr> <chr>
1  93.0  33.4 SI_EF_TI… 3.54  4.10  5.16  5.78  6.29  6.08  6.25  5.84 
2  93.0  33.4 SI_EF_TI… 4.88  5.11  5.84  6.03  6.19  5.87  6.08  5.92 
3  93.0  33.4 SI_EF_TI… 5.69  5.64  6.06  5.91  5.77  5.39  5.62  5.65 
4  93.0  33.4 SI_EF_TI… 6.17  5.87  5.95  5.49  5.13  4.71  4.94  5.14 
5  93.0  33.4 SI_EF_TI… 5.58  4.76  4.07  3.03  2.38  2.12  2.24  2.63 
6  93.0  33.4 SI_EF_OP… 6.30  5.87  6.06  6.04  6.30  6.08  6.25  5.94 
7  93.0  33.4 SI_EF_OP… 60.00 51.00 36.00 19.00 5.00  0.00  2.00  12.00
8  93.0  33.4 SI_EF_TI… S     S     S     S     S     S     S     S    
# … with 5 more variables: SEP <chr>, OCT <chr>, NOV <chr>, DEC <chr>,
#   ANN <chr>
```

**Comment by olugovoy** [comment]
Got it, thanks! It looks like the list of parameters is not actual, and until updated, it is good to check them with NASA/POWER web query..

**Comment by adamhsparks** [comment]
I'm struggling with the API on this sort of issue. I don't have a good way to validate requests before sending them if this is the case.

Thanks for the help. I did find several bugs while sorting this out and am prepping a new release.
