### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by mladencucak** [ropensci/nasapower#39]
https://ropensci.github.io/nasapower/articles/nasapower.html

**Comment by adamhsparks** [comment]
Hi Mladden, I know that link no longer works, but where is it linked from so I can fix it?

**Comment by adamhsparks** [comment]
I found an instance in the README, is that it?

**Comment by mladencucak** [comment]
I was just looking for it, but could not find it again. Yes, I was looking for vignettes and readme files....
