### ISSUE TITLE
Error while using R to access the API

### ISSUE THREAD

**Issue by jyumbya** [ropensci/nasapower#40]
I just followed the example provided in the package to access daily data, see below.

```
library(nasapower)
daily_single_ag <- get_power(community = "AG",
                             lonlat = c(151.81, -27.48),
                             pars = c("RH2M", "T2M", "PRECTOT"),
                             dates = c("1985-01-01", "1985-01-31"),
                             temporal_average = "DAILY"
)

daily_single_ag

```
It through the error below

```
Error: 
Something went wrong with the query, no data were returned. Please see <https://power.larc.nasa.gov> for potential server issues.
```

**Comment by adamhsparks** [comment]
This doesn't appear to be related to `nasapower`. As the error message I've coded says, "no data were returned", which means there's an issue with the API.

Here's the URL response that `nasapower` is getting from the API:
https://power.larc.nasa.gov/cgi-bin/v1/DataAccess.py?request=execute&identifier=SinglePoint&parameters=RH2M,T2M,PRECTOT&startDate=19850101&endDate=19850131&userCommunity=AG&tempAverage=DAILY&outputList=CSV&lon=151.81&lat=-27.48&user=nasapower

You can see that it does not have any data. If it were properly responding you'd have a CSV file to download.

cheers!
