### ISSUE TITLE
ICASA headers and columns not aligned

### ISSUE THREAD

**Issue by marcoslana1** [ropensci/nasapower#41]
Hi! Thanks for the package! When creating the files for DSSAT (ICASA format) headers and columns are not in the alignment that the model requires. In the attached file, the first sequence depicts the working structure, and below the structure generated by create_icasa.
How can I adjust these alignments?
Thanks in advance!
[new 1.txt](https://github.com/ropensci/nasapower/files/3709283/new.1.txt)

**Comment by adamhsparks** [comment]
Thanks for alerting me and thank you for the example. 

I'll look into it and see what I can find out and get it fixed.

**Comment by adamhsparks** [comment]
@marcoslana1, can you go to https://power.larc.nasa.gov/data-access-viewer/ and generate the ICASA file and check that and let me know if it's properly formatted?

`nasapower` only puts together an API query and downloads what the POWER team serves. It's not modifying the file in any way AFAIK.

**Comment by marcoslana1** [comment]
Hey @adamhsparks ! Thanks for checking this. No, the ICASA file downloaded from the https://power.larc.nasa.gov/data-access-viewer/ also comes in a non-suitable format. I will check with them. Cheers

**Comment by adamhsparks** [comment]
I thought this was the case. 

Hopefully they can fix it.
