### ISSUE TITLE
Calls to the API are returning an error

### ISSUE THREAD

**Issue by jyumbya** [ropensci/nasapower#42]
Calls to the API all day are returning the error below:

`Error: 
Something went wrong with the query, no data were returned. Please see <https://power.larc.nasa.gov> for potential server issues.`

**Comment by jyumbya** [comment]
I have just installed the development version and it worked great. Thanks!

**Comment by adamhsparks** [comment]
The development version only has minor changes to the documentation, nothing to the API client itself.

If you checked the POWER webpage yesterday there was a notice that the data were unavailable. It seems that has now been fixed.

Glad it's all working now!
