### ISSUE TITLE
DOY column: dates and formatting

### ISSUE THREAD

**Issue by AboodaA** [ropensci/nasapower#43]
<details> <summary>The below code gives the error that the DOY column (day of year?) is uninitialised, but I do not see how the date could be any differently formatted. </summary>

``
> oceanic2 <- nasapower::get_power(community = "SSE", lonlat = c(3.9, 52.5), pars = "T2M", dates =c("1999-01-01", "2000-01-01"), temporal_average = "DAILY")

Error in `$<-.data.frame`(`*tmp*`, "DOY", value = integer(0)) : 
  replacement has 0 rows, data has 366
In addition: Warning message:
Unknown or uninitialised column: 'DOY'. 

</details>

**Comment by adamhsparks** [comment]
Confirmed. Seems to be an issue with the SSE community. I'll have to look into this some more.

**Comment by AboodaA** [comment]
Thanks!

**Comment by adamhsparks** [comment]
I've found the bug. The POWER data dates aren't served in a uniform format for all communities. Somehow this escaped my tests, but also baffles me as to why the dates are different formats for different communities.

I'll get it fixed and get a new release on CRAN.

**Comment by adamhsparks** [comment]
I've pushed a tentative fix if you are willing to try and report back to me?

You can install from this repository using GitHub.

`devtools::install_github("ropensci/nasapower")`

A new release should be on CRAN this weekend or early next week.

**Comment by AboodaA** [comment]
This works from the version I just pulled. At least, with the same code snippet I tried earlier. Awesome.
