### ISSUE TITLE
Not all parameters can be handled 

### ISSUE THREAD

**Issue by AboodaA** [ropensci/nasapower#44]
Trying to run the below code gives an error when the parameter for solar irradiance is defined as "ALL SKY TOA SW DWN"; I get a similar issue with "SI_EF_MIN_OPTIMAL".  

In the first case, I get an error message that the "all sky" string is not a valid parameter. In the second, I get an error message that the SI EF min Optimal returns not an energy but an orientation for the panels. In both cases, this is at odds with the documentation on the NASA Power API website. It is possible that these values do not work with the "climatology" temporal average but if that is the case (I have yet to try out others) this is not spelled out clearly in anything I can find. 

Thanks! 

<details> 

<summary><strong>Session Info</strong></summary>

```r
get_power(community = "SSE", pars = c("TS", "ALLSKY_TOA_SW_DWN"), temporal_average = "CLIMATOLOGY", lonlat = c(averagelon, averagelat))
```
</details>

**Comment by adamhsparks** [comment]
Can you provide an actual (non)working example? the `lonlat` values provided are not valid.

**Comment by AboodaA** [comment]
Sorry, that was my mistake. Please see the code below. 
``
#this works 
> qatarrandom1 <- nasapower::get_power(community = "SSE", pars = "ALLSKY_SFC_SW_DWN", temporal_average = "CLIMATOLOGY", dates = c("2000-01-01", "2010-01-01"), lonlat = c(51, 25.1))
#this does not 
> qatarrandom2 <- nasapower::get_power(community = "SSE", pars = "SI_EF_MIN_OPTIMAL", temporal_average = "CLIMATOLOGY", dates = c("2000-01-01", "2010-01-01"), lonlat = c(51, 25.1))
### 

The error message for the second one is as below
``

Error: The Solar Irradiance for Equator Facing Tilted Surfaces are returned as a Set of Surfaces., Please remove: SI_EF_MIN_OPTIMAL and replace with SI_EF_MIN_TILTED_SURFACE to return the requested parameters., Please remove: SI_EF_MIN_OPTIMAL and replace with SI_EF_TILTED_SURFACE to return the requested parameters. Please reference our API Documentation at https://power.larc.nasa.gov for more information.
--
 
  |

**Comment by adamhsparks** [comment]
That's not an error from this package, that comes directly from the POWER API as far as I can tell.

Did you follow the directions the error message gives you? What was the result then?

**Comment by AboodaA** [comment]
Hi, sorry for the late reply. I did indeed try to work this through but I
think this is a more meaningful error. The documentation on the website
suggests that what I get for the query string is at odds with the reply
from the API in this case.

What is the procedure for flagging this?

**Comment by adamhsparks** [comment]
I'm not sure what I'm supposed to do here? `nasapower` only creates a query it sends to the API. If the API isn't handling the parameters properly then that's on the receiving side, not the sending side and I have no control.

**Comment by AboodaA** [comment]
I see your point and I am sorry for the hassle. I will close this and try to find a way of following up with the NASA Power API. Their website is not entirely clear on how to do this (maybe I didn't look in the right places) so I would appreciate any pointers you have on that.

**Comment by adamhsparks** [comment]
I've just sent an email to the team members, they're responsive in the past. If there is something that they suggest that I can implement I'm happy to. But this doesn't seem to be under my control
