### ISSUE TITLE
Error in curl::curl_fetch_memory

### ISSUE THREAD

**Issue by victofs** [ropensci/nasapower#45]
I am trying to run these lines of code (provided as example on readme.md).

```
if (!require(devtools)) {
  install.packages("devtools")
}
devtools::install_github("ropensci/nasapower",
                         build_vignettes = TRUE)

#install.packages("nasapower",dep = T)
library(nasapower)

daily_ag <- get_power(community = "AG",
                      lonlat = c(151.81, -27.48),
                      pars = c("RH2M", "T2M", "PRECTOT"),
                      dates = "1985-01-01",
                      temporal_average = "DAILY")

```
However, after a minute (or more) of waiting, i click on the stop button and the following returns:

> Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
>   Operation was aborted by an application callback

I have been running these same lines of code before and it was working flawlessly, but since yesterday i get these error returns. There is any server instability these days?

**Comment by adamhsparks** [comment]
Please check the POWER website for issues with the server. This package is only a client for the API. 

This currently appears on the site.

> NOTICE

> POWER data access appears to be temporarily unavailable. Parameter information and data may be inaccessible at this time. Please try again shortly and we apologize for this inconvenience. If you have any questions please do not hesitate to contact the POWER team.
