### ISSUE TITLE
New link for the parameters.json

### ISSUE THREAD

**Issue by BradleyPOWER** [ropensci/nasapower#48]
Hello, 

I am a developer with the NASA POWER Project and would like to let you know that there is a new link for the parameters.json file. We had to change hosing environments and that required some changes to the URL's structure. 

**Please use the following link in your application:**
- https://power.larc.nasa.gov/system/parameters.json

**Replacing:**
- https://power.larc.nasa.gov/RADAPP/GEODATA/powerWeb/POWER_Parameters_v110.json

Other Links:
- https://power.larc.nasa.gov/docs/
- https://power.larc.nasa.gov/docs/methodology/

**Comment by adamhsparks** [comment]
Thanks! I've updated the `data-raw` file and internal data.

This will be included in the next release.
