### ISSUE TITLE
Migrate to  Web Services Portal Version 2 by 2021-07-01

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/nasapower#52]
The POWER team are migrating to a new API by 2021-07-01, https://power.larc.nasa.gov/beta/docs/services/api/

v4.0 will take advantage of this new functionality.

- [x] Implement new API V2 calls
- [x] Implement new functions to take advantage of the new manager API providing information on parameters
- [x] Consolidate, standardise and optimise functions that may be shared between `get_power()` and the new `query_parameters()`
- [x] Write tests for new and revised functions
- [x] Update vignette to reflect new functionality of _nasapower_ and the POWER API V2
- [x] Check functionality against the new API, _e.g._ rate limits as reported in https://github.com/ropensci/nasapower/issues/52#issuecomment-899129382

**Comment by olicoste** [comment]
Hi,

Now that it has migrated to the new API, how can I amend my R code to make it work?

**Comment by adamhsparks** [comment]
It hasn't been migrated to the new API yet. I've not had time to finish this work and release v4.0.0 yet, sorry.

**Comment by olicoste** [comment]
Hi, Ok, thanks for the fast answer. 
I thought this was why I got an Error 422 when requesting data with get_power function. Do you know where this could come from?

**Comment by fe-neculqueo** [comment]
I got an Error 442 too. What I should do?

**Comment by adamhsparks** [comment]
You have three options, i) wait for me to have time to complete the rewriting of the _nasapower_ package to work with the new POWER API, ii) access the data directly through the POWER website and download it in your browser or iii) write your own API calls to access the data in R.

I'm doing this in my own personal time and am working on it as fast as I possibly can. This is not a funded or work project in any way. I spent several hours yesterday already working on it and made good progress. I hope to have a beta version shortly.

**Comment by LucasJorgeAbdala** [comment]
I have been receiving the same mistake. I hope it is something easy to fix adam!! This is great work. 

Thanks!!

**Comment by adamhsparks** [comment]
Not as easy as a fix as I'd like. I'm rewriting a fair portion of the package's code, but I've made more good progress this AM. I've managed to send a query and parse it using the new code. I'll hope to have something you can try soon.

**Comment by adamhsparks** [comment]
I've a working beta version! This is a work in progress, so there are functions that **DO NOT YET WORK**! But you should be able to start converting old scripts to use the new POWER API V2 functionality now for point data.

If you need access or want to try and would like to give feedback, _e.g._ report bugs, then here are the instructions.

Install the development version from GitHub that I've been working on, <https://github.com/ropensci/nasapower/tree/API_V2>.

```r
if (!require("remotes")) {
  install.packages("remotes")
}

remotes::install_github("ropensci/nasapower",
                         ref = "API_V2"
)
```

Then fetch POINT data for the daily API endpoint.

```r
library("nasapower")
daily_ag <- get_power(community = "ag",
                      lonlat = c(151.81, -27.48),
                      pars = c("RH2M", "T2M", "PRECTOTCORR"),
                      dates = "1985-01-01",
                      temporal_api = "daily"
                      )
daily_ag
```

Note that I have made changes to the functions to correspond to changes in the API. The `get_power()` now requests `temporal_api` rather than `temporal_average` and the precipitation (for those of you using rainfall) is now "PRECTOTCORR" rather than "PRECTOT". I've not made any other user-facing changes yet aside from adding new arguments to `get_power()` for wind. **These new parameters for wind have not yet been tested but are documented in the `get_power() help file.**

Please try it out and let me know what you may find. Currently, as far as I know, the POWER team has only enabled POINT data so you should get an error if you request something out of scope, but for example, this works (for me).

Happy downloading!

**Comment by LucasJorgeAbdala** [comment]
I have just try it, and it is working perfectly. So far, i did not find any bugs. Will let you know if something appears. Thanks for your effort adam! This is a great package.

**Comment by xianranli** [comment]
Great work Adam! One issue I encountered is the server would only allow 5 queries, which would break the loop for many requests. The solution I currently used is to put Sys.sleep(10) in the loop, which continues but slow down the process.

**Comment by adamhsparks** [comment]
Thanks, I've not yet tested this but will do some checking of the POWER documentation and adjust the _nasapower_ documentation and functionality accordingly.

**Comment by adamhsparks** [comment]
I've reached the point where I've merged the new feature branch into `devel` now and updated the installation instructions.

I think all the major functionality is now in place with tests and the vignette also completed.  The last bit left is to check any rate-limiting. I know the POWER team has some documentation about not hitting the server too hard, I've written the client to make only one query per point as they've requested, but have no other built-in rate limits as yet.

**Comment by olicoste** [comment]
It works for me too, that is an awsome job. Thank you for taking some of your personal time to fix that. So far no problem for me but for sure I'll let know if something pops up.

**Comment by adamhsparks** [comment]
v4.0.0 has been submitted to CRAN. Just awaiting them to action the approval.

**Comment by jizarten** [comment]
Hi Adam,

1. I've tried to retrieve daily precipitation (i.e., PRECTOTCORR) data for Ugandan districts for several years (i.e., 2000 to 2020) both through the API and the web data access viewer but I always get -999 as a value for all the observations. Any idea why this is happening?
2. I also wonder if it's possible to retrieve averaged data for polygons using a shapefile. If there is grid/raster data available for a continent/country for ag data (e.g., precipitation, temperature, radiation), I can do the averaged extraction myself but I'm not sure if this is something that can be done.

Thank you.
Best, 
Jorge

**Comment by adamhsparks** [comment]
Hi Jorge,
This issue is closes. Please open a new one for new issues like these.

1. Please see the POWER website for their statement regarding the precipitation being corrupted.
2. No. This is only an API client. I don’t do any manipulation other than reformatting and replacing `NA` values with `NA`.

**Comment by LucasJorgeAbdala** [comment]
I am having the same problem with the -999 for precipitation. But is working very good everything!

**Comment by adamhsparks** [comment]
Yes, the -999 for precipitation is a known-bug. I've fixed it in the devel branch. The next release will not report -999 for invalid values and hopefully by then the precipitation is fixed in the POWER data.

**Comment by andresouzaesilva** [comment]
I'm getting the 422 error, but my code is in Python, then the code shows 429, is there any Python update ready already? Thank´s

**Comment by adamhsparks** [comment]
If you’re getting a 422 error with _nasapower_, this R package, then you need to update your installed version to use the new version of the POWER API. Otherwise, I’m not able to provide you with assistance for any other programming languages.
