### ISSUE TITLE
Error: Unprocessable Entity (HTTP 422) 

### ISSUE THREAD

**Issue by Yonaba** [ropensci/nasapower#54]
**Describe the bug**
I have been using nasapower for a while and it was working fine until a few weeks ago, when any attempt to retieve climate data through `get_power` fails, returning the following message: "Error: Unprocessable Entity (HTTP 422)".

**Code to Reproduce**
With the following example :

`library("nasapower")
daily_ag <- get_power(community = "AG",
                      lonlat = c(151.81, -27.48),
                      pars = c("RH2M", "T2M"),
                      dates = "1985-01-01",
                      temporal_average = "daily"
)
daily_ag`

An error message is returned.
**"Error: Unprocessable Entity (HTTP 422)**

**Expected behaviour**
I was exepecting a tibble to be returned, containing RH2M and T2M values.

**OS and R versions**
 - OS: Windows 10
 - R Version : 4.1.1 / RStudio : 1.4.1717

I also tried re-installing the package, didn't help.
Any help would be very much appreciated, thanks.

**Comment by Yonaba** [comment]
Finally, problem solved. I just had to update the package _nasapower_ from github, not from CRAN.
Works fine now.

**Comment by adamhsparks** [comment]
Sorry, I’m still waiting on CRAN. I submitted the new update yesterday.

**Comment by Yonaba** [comment]
Great. I have noticed that running get_power in a loop results in an error after 5-6 requests. I have a list of 54 countries, and I get the data all at once. After each 5-6 countries, I receive the following error:

_"Error: Something went wrong with the query, no data were returned. Please see <https://power.larc.nasa.gov> for potential server issues."_

I believe it has to do with the server being a bit overloaded though.

**Comment by adamhsparks** [comment]
Yes. The new API has limits on it now whereas the old one didn’t appear to. As it’s written nasapower won’t trigger any issues, but other users have indicated that this may be a problem with repeated queries and that a `Sys.sleep(10)` in a loop may be a good idea.

In the future I’ll have something in a vignette on how to query in a loop, lapply, etc. but the POWER team didn’t document anything that I could cite properly or use in the package to slow it down within reason so for now it’s anecdotal, but yours matches others so far from what I’ve seen.

>

**Comment by Yonaba** [comment]
Ah, perfect. Included it in my script.
Thanks for the swift support!
