### ISSUE TITLE
Error: Unprocessable Entity (HTTP 422)

### ISSUE THREAD

**Issue by agronomofiorentini** [ropensci/nasapower#59]
**Describe the bug**
Hi,
Thanks to develop this amazing R package.
I am trying to retrive the data as always but now the console gives me as output

"Error: Unprocessable Entity (HTTP 422)"

Do you know what is happening?
Maybe is a issue of the server side?

**Code to Reproduce**

`
daily_single_ag_1 <- get_power(community = "AG",
                               lonlat = c(8.465008, 40.62127),
                               pars = c("T10M_MAX", "T10M_MIN"),
                               dates = c("2000-01-01", "2019-12-31"),
                               temporal_average = "CLIMATOLOGY")

`

**OS and R versions (please complete the following information):**
 - Windows10
 - R Version 4.0.5

**Comment by adamhsparks** [comment]
Hi, I'm unable to duplicate your issue.

```r
[ins] r$> get_power(community = "AG",
          lonlat = c(8.465008, 40.62127),
          pars = c("T10M_MAX", "T10M_MIN"),
          dates = c("2000-01-01", "2019-12-31"),
          temporal_average = "CLIMATOLOGY")

                                                                                                                                                                                                        NASA/POWER CERES/MERRA2 Native Resolution Climatology Climatologies
 30-year Meteorological and Solar Monthly & Annual Climatologies (January 1990 - December 2019)
 Location: Latitude  40.62   Longitude 8.465
 Elevation from MERRA-2: Average for 0.5 x 0.625 degree lat/lon region = 347.73 meters
 Value for missing model data cannot be computed or out of model availability range: NA
 Parameter(s):

 Parameters:
 T10M_MAX     MERRA-2 Temperature at 10 Meters Maximum (C) ;
 T10M_MIN     MERRA-2 Temperature at 10 Meters Minimum (C)

# A tibble: 2 × 16
    LON   LAT PARAMETER   JAN   FEB   MAR   APR   MAY   JUN   JUL   AUG   SEP   OCT   NOV   DEC
  <dbl> <dbl> <chr>     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1  8.47  40.6 T10M_MAX  19.5   21.9 26.9  30.2  35.1  37.6   39.6  40.1  36.3  31.7 24.8  20.2
2  8.47  40.6 T10M_MIN  -2.25  -2   -1.22  2.23  5.33  9.99  12.2  14.0  10.5   6.2  0.37 -2.19
# … with 1 more variable: ANN <dbl>
Warning message:
`temporal_average has been deprecated for `temporal_api`.
Your query has been modified to use the new terminology for `get_power`.  Please update your scripts to use the new argument.
````

**OS and R versions**
* macOS 11.5.2
* R Version 4.1.1

**Comment by agronomofiorentini** [comment]
It persists also today.

I think also that is a server hiccup.

I will try the next days and i will let you know.

Thanks for now.

**Comment by adamhsparks** [comment]
Sorry, I'm unsure what the issue may be. I just checked again from a different location this time and it went through just fine again.

**Comment by agronomofiorentini** [comment]
I have tried the follow locations
1. -3.708775, 40.39869
2. 9.220103, 45.49171
3. -74.24465, 40.65252

The problem persists.

So I have installed again the nasapower package and now it works fine for the temperature parameters, while for the PRECTOT parameters didn't call any values.

infact the console gives me 

`temporal_average has been deprecated for `temporal_api`.
Your query has been modified to use the new terminology for `get_power`.  Please update your scripts to use the new argument.Errore: PRECTOT is/are not valid in 'pars'.
Check that the 'pars', 'community' and 'temporal_api' align.

So i changed the PRECTOT with the PRECTOTCORR but the value that i am getting from the original position is quite strange:
-999.

Sorry to keep bothering you

**Comment by adamhsparks** [comment]
Yes, the precipitation values are corrupted. The POWER webpage did have a notice that this had occurred but that's since disappeared from their page today, however, I note that the values are still not valid for precipitation.

**Comment by agronomofiorentini** [comment]
It's strange.

I have tried also a new location (13.45042, 43.59642) always in italy and the results is always the same.
-999.

What do you think it is better to wait a week and try again or contact the nasapower to report this problem referencing this issue?

**Comment by adamhsparks** [comment]
From what I understand, the precipitation values are currently corrupted. You will have to wait until they have fixed them or find another resource, _e.g._ [_chirps_](https://github.com/ropensci/chirps) for precipitation data.

**Comment by agronomofiorentini** [comment]
Thanks a lot.

Marco

**Comment by adamhsparks** [comment]
Hi Fernando,
At the bottom of the README for this repository I've this bullet point, maybe the link helps?

> The U.S. Earth System Research Laboratory, Physical Science Division of the National Atmospheric & Oceanic Administration (NOAA) maintains a list of gridded climate data sets that provide different data and different resolutions [psl.noaa.gov/data/gridded]https://psl.noaa.gov/data/gridded/).
