### ISSUE TITLE
Fetching global climatology data

### ISSUE THREAD

**Issue by Varsha-Ujjinni-VijayKumar** [ropensci/nasapower#60]
Hey Adam,

I was just trying to retrieve the global data for climatology and I keep getting the following error:

`get_power(community = "ag", pars = "PRECTOTCORR", lonlat = "global", temporal_api = "climatology")`

Error: The POWER team have not enabled global data queries with this version of the 'API'.

Here is my sessionInfo:

Session info ------------------------------------------------------------------------------------------------
setting value
version R version 4.0.4 (2021-02-15)
os Windows 10 x64
system x86_64, mingw32
ui RStudio
language (EN)
collate English_Australia.1252
ctype English_Australia.1252
tz Australia/Sydney
date 2021-09-13

I am not sure what I might be doing wrong? Thank you.

**Comment by adamhsparks** [comment]
See the POWER documentation here: https://power.larc.nasa.gov/docs/services/api/temporal/

> At the moment we currently have only implemented the Point spatial option on all the Temporal APIs. We will be adding enhancements in the future.

>

**Comment by Varsha-Ujjinni-VijayKumar** [comment]
Hey, 
Got it ! Sorry about that. Thank you.
