### ISSUE TITLE
Problems with installation 

### ISSUE THREAD

**Issue by agryji08** [ropensci/nasapower#61]
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/ropensci/nasapower/tarball/master'

 - OS: Windows10
 - MRO 4.02

**Comment by adamhsparks** [comment]
Hi, could you please provide me with a reproducible example so I can see the code that is causing the issue you're having?

https://aosmith16.github.io/spring-r-topics/slides/week09_reprex.html#1

**Comment by adamhsparks** [comment]
Closing this issue. Please reopen and add requested information if it continues to be an issue.
