### ISSUE TITLE
Can I access HQPRECIPITATION ? 

### ISSUE THREAD

**Issue by danielreispereira** [ropensci/nasapower#62]
**Describe the bug**
Can not download High Quality Precipitation (IMERG HQPRECIPITATION).
If "HQPRECIPITATION" is part of the parameters list, I should be able to download it

**Code to Reproduce**
```
#get params
parameters <- nasapower::query_parameters(community = "AG", temporal_api = "DAILY")

#explore parameters (I can see that there are two precipitation sources: IMERG and MERRA2 (PRECTOTCORR and HQPRECIPITATION
parameters$HQPRECIPITATION
parameters$PRECTOTCORR

#download both precip data to compare
ag_d <- get_power(
  community = "AG",
  lonlat = c(151.81, -27.48),
  pars = c("PRECTOTCORR", "HQPRECIPITATION"),
  dates = "1985-01-01",
  temporal_api = "DAILY"
)
Error: HQPRECIPITATION is/are not valid in 'pars'.
Check that the 'pars', 'community' and 'temporal_api' align.
```

**Expected behaviour**
Both precipitation downloaded. Get error instead.

**Comment by adamhsparks** [comment]
Hi @danielreispereira, it looks like this parameter was added since I last updated the internal list of available parameters that _nasapower_ checks against before sending a query.

I've updated the internal list in the `devel` branch here, but the API isn't responding with any data for me right now to do a proper test.

This should install the development version of _nasapower_ from that branch if you'd like to test.

````r
if (!require("remotes")) {
  install.packages("remotes")
}

remotes::install_github("ropensci/nasapower", ref = "devel")
```

**Comment by adamhsparks** [comment]
danielreispereira, I'm trying to find this "HQPRECIPITATION" var in the current list of available values. However, when I fetch the most recent information from the POWER API, I cannot find this particular var in any of the supplied temporal API/community combinations. I suspect that the POWER team has changed the data availability in the API.

This is probably why it's not in the version I had locally but did exist in the CRAN version. I will try to get an update on CRAN soon, I still need to get an update out with the rate-limiting functionality as well.

See example below indicating that the requested parameter does not exist.

``` r
 library(purrr)
 library(jsonlite)
 
 temporal_api <- c("HOURLY", "DAILY", "MONTHLY", "CLIMATOLOGY")
 community <- c("AG", "RE", "SB")
 
 # create all combinations
 vals <- expand.grid(temporal_api, community, stringsAsFactors = FALSE)
 
 # create equal length vectors for purrr::map2
 temporal_api <- vals[, 1]
 community <- vals[, 2]
 
 base_url <- "https://power.larc.nasa.gov/api/system/manager/parameters?"
 
 power_pars <- map2(.x = temporal_api,
                    .y = community,
                    .f = ~ fromJSON(paste0(
                        base_url,
                        "temporal=",
                        .x,
                        "&community=",
                        .y
                    )))
 
 purrr::map_lgl(.x = power_pars,
                .f = ~ any("HQPRECIPITATION" %in% .))
 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[12] FALSE
```

**Comment by adamhsparks** [comment]
Closed with https://github.com/ropensci/nasapower/commit/a03aca170d64e0915495fd2fdf3e975404f56dd7
