### ISSUE TITLE
Warning with vroom >= 1.5.0

### ISSUE THREAD

**Issue by palderman** [ropensci/nasapower#66]
Current released version (4.0.3) is throwing a warning with `readr::read_lines()` and `readr::read_csv()` when running tests in my new R package under development at [https://github.com/palderman/weathRman](https://github.com/palderman/weathRman):

```
  The `file` argument of `vroom()` must use `I()` for literal data as of vroom 1.5.0.

  # Bad:
  vroom("foo\nbar\n")

  # Good:
  vroom(I("foo\nbar\n"))

```

**Code to Reproduce**
Clone my repo [https://github.com/palderman/weathRman](https://github.com/palderman/weathRman) and run all tests Ctrl + Shift + T in RStudio IDE.

**Expected behaviour**
No warnings.

**OS and R versions (please complete the following information):**
 - OS: Linux, Ubuntu 18.04 LTS
 - R Version 4.1.2

**Comment by adamhsparks** [comment]
I've merged the PR and submitted a new patch release to CRAN. I will close this when that version is accepted.

**Comment by palderman** [comment]
Sounds good! Thanks for your work developing/maintaining this package.

**Comment by adamhsparks** [comment]
Thanks for your help, I've noted your contribution in the authors list. https://docs.ropensci.org/nasapower/authors.html

I'll get in touch next time I'm in OK. My family lives in Stillwater now. :)

**Comment by palderman** [comment]
Thanks for the acknowledgement.

What a small world! Please do reach out next time you are in Stillwater. I see from your ORCID profile that you are a plant pathologist by training and you spent some time in Toowoomba? Did you happen to interact with any of the APSIM modeling group there? I'm a crop modeler, myself, and have been interested in developing improved approaches for modeling crop-disease interactions. Anyway, it seems like we could have a fun conversation next time you are in town!

**Comment by adamhsparks** [comment]
I’ve interacted with the APSIM folks, a good mate, still in Toowoomba is on the APSIM Panel and I’ve an APSIM modeller in my team here in Perth. I’ve been interested in ways of integrating disease loss functions into crop growth models, so yes, we probably could have a fun discussion next time I’m in town.
