### ISSUE TITLE
Error in calculating wind direction at daily level 

### ISSUE THREAD

**Issue by makorb** [ropensci/nasapower#77]
Hey!

I noticed that when you use the get_power() command to extract the U, V and wind direction components at the daily level, the wind direction is incorrect. This issue is not present at the monthly level, so there must be some error in calculation at the daily level. 

Code:

#at daily level
daily_wind <- get_power(community = "ag",
                      lonlat = c(39.8006, 8.247),
                      pars = c("U2M", "V2M", "WD2M"),
                      dates = c("2008-01-01"),
                      temporal_api = "daily"
)

#manually calculating wind direction using u and v components
atan2(-daily_wind$U2M, -daily_wind$V2M)*180/pi #note does not match WD2M 

 - OS: macOS
 - R version 4.1.2 (2021-11-01)

**Comment by adamhsparks** [comment]
Hi there! I'm afraid that you may have found an error in the API itself. {nasapower} does not do any calculations with the data; it simply requests and returns formatted data in your R session.
