### ISSUE TITLE
Error retrieving hourly data for regional coverage

### ISSUE THREAD

**Issue by saulo1305** [ropensci/nasapower#80]
Tried to retrieve hourly data from multiple points:

```
dadosMerra <- nasapower::get_power(community = "re",
                                   lonlat = c(-42.7,-4.7,-38.5,-2.3),
                                   dates = c("2020-01-01"),
                                   temporal_api = "hourly",
                                   pars = c("U50M", "V50M", "PS", "QV10M"))
```

Got the following error:

```
Erro: lexical error: invalid char in json text.
                                       <!DOCTYPE html>  <html>  <head>
                     (right here) ------^
```

OS Windows
R 4.3.1
nasapower 4.1.0

**Comment by adamhsparks** [comment]
This is a mistake in my user-input checks. Regional data requests are not supported for hourly data.

See the Swagger page for reference: https://power.larc.nasa.gov/api/pages/?urls.primaryName=Hourly

I'll get this corrected.

**Comment by adamhsparks** [comment]
*edit* this link shows a table of availability more clearly. https://power.larc.nasa.gov/docs/services/api/temporal/

**Comment by adamhsparks** [comment]
Fixed in https://github.com/ropensci/nasapower/releases/tag/v4.2.0
