### ISSUE TITLE
Issue querying POWER API for all parameters in a community + temporal API

### ISSUE THREAD

**Issue by emmalink1** [ropensci/nasapower#85]
I am attempting to use the query_parameters function to learn about the parameters available within communities/temporal_apis. Currently, an error is produced when following the example code provided in the function documentation to fetch attribute information for all parameters: 

> nasapower::query_parameters(community = "ag", temporal_api = "hourly")
Error in nasapower::query_parameters(community = "ag", temporal_api = "hourly") : 
  argument "pars" is missing, with no default

I'm using: 
 - OS: Windows 11
 - same behavior in R Versions 4.3.2 and 4.4.0

**Comment by adamhsparks** [comment]
Thanks for catching and reporting this! I'll push to CRAN shortly but you can install the version from GitHub if you would like to have access before it's on CRAN.

```r
install.packages("nasapower", repos = "https://ropensci.r-universe.dev")
```
