### ISSUE TITLE
Contribution to project

### ISSUE THREAD

**Issue by Gonzalo1985** [ropensci/nasapower#87]
Hello. I work in the Nat Meteorological Service of Argentina. I would like to know if the project is open to contribution. I am thinking of function for evaluation of the nasa power product with local data. Also it could be an option a bias correction to the global model with local data input. I am thinking some functions to the package with this kind of implementation. Would it be a good option?

Thank you,

Kind regards,
Gonzalo

**Comment by adamhsparks** [comment]
Hola, @Gonzalo1985!
Thanks for your interest in contributing to {nasapower}. I'm sorry, but I want to keep this package as an API client only. However, I do see the value in what you proposed and I am happy to contribute to the development of other R packages that leverage this client library, _e.g._, [{PowerSDI}](https://github.com/gabrielblain/PowerSDI). So if you decide to create an R package that offers this functionality, feel free to include me in the development team and I'll contribute as I can.

**Comment by Gonzalo1985** [comment]
Thanks @adamhsparks !

I have already create a package in R for the exploration of WRF model data from Argentinian meteorological service, but the package also has multiple linear regression implementation for correction of outputs. If you want to take a look here is the link: github.com/Gonzalo1985/aws.wrfsmn
